spring:
  application:
    name: product-application
server:
  port: 8091
cloud:
  config:
    uri: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true
